---
language: python
python:
- 2.7
env:
global:
- secure: "jGJF0g45E8W7gHr4/GWZhnIMNqnl8OfX7yF28hb+nooC8AHJMMa4o623mHGErkfXGhQIWBmSVvyBPskru0o8oRuDrSU8KtzYFoS0G1CWX7runktku6NkR0LRPxhuuYqzgEohxeIBoyZxzd9Z4uEDOG7tuErECWxmVp4Xr6jl/hBakepN+k/yWMBjlzi8zdPiFUjZKy6a6v71xak+mhcd9bWO4mrasOuA9exuKdcyitFxu4ZszwCGQkqKHT0QOwh9C32dVuDiyl7PlqXMrZyj5KpeymVy44nj7iCtgas7omJdMgqiYsz3KO1ufl2OhJihFOSgrsK0C4pnGHeLCdqVLsP2B3qZr+e7eBERQLIWMOYOcqPvQ1GC7ctv40JRGv7MsiB+U34U2iDuqQs5hzDeR0QvD7HJBsEBwA2GVSbV36ki15LS8wrRU4/kwnfoKcwbyvqYRnXwxvNYaZw+yUZaxZlgQQUnURSUlgFgB0nIGCLebcRN0VZvQL1yLVoixFOqGb2PMTQsNu1QAi4XGma4N0YumyJZ/dObk9IrX0AUqyBreUf487uz6C02CLiXAVCGuntJRZqbL4NHvI7lyZfdIVPRBcNF/thb6gE2RRaAinQFN1BnjcDLTUXxSBkH8u2ZiwEYb2ZSrVk7tjnPQjIDq5Hzo8QR9Kj8hLPCeaKZPVc="
- secure: "brqA6jhDr/l6bvqh9ErMOsgrppbTQETZvtU/cL+4WGmtbUFpUM+mH/Ek/2PMqxwweujFs1FLxT1AUrXtw+xkkrfZqBjI5TWoHznYpvBkdyCydIDy0uraPSOL58+dbzXp/hTW9V9INNI2doHP6u+8wDly+is8pKzL2DB5Z4THSGTgg4uNifwTGkSeqpRPlVelX8FPBkEZ4dU7raAnns+lFmyij5bmRD/WAdXvm3lXmxgi3mvHYWL1N9ncbG4UjHQkTDEbZzfrNyyb5wPzKt2FWd0P1UCgIdGURREriQjo4TRxE1zD2G2mTeaK1ltoC5TN3pM4zRYuL5Ff261eNapjkZUkp0iTdRez7hL/ZFBb+pYK5XerMuE505KIUoEgtjT7gYjQEFwqAxTyvJt9+Z9yPiCNLXVgKeTgG0AnQG7O5KJuTYaTt27S2ruAf938Fujjmn5iyi4DINRXKnPSKVpN/wt1/cY+AdHLXboeAdSymjH/BNZqUCgL/A+K/9m/mCF9TAug1MkKBOTGAL4GC/+z0Op3ecqGzbeI8w1W6p7lZVgiQbIex8FO97noZ3vJm3ljr8B7Q1uFtoHd9Tl4VmlS60F8wzhwrJ6SZXwJLnGS/exk+Z9kPxgSpzUL5LuHGFwvQdtbteNomFhcJ9Q+xrzrPei7rDhMxsPGKCZ7+U2j5JY="
services:
- docker
install:
- docker build -t danwp .
- docker run -d -p 127.0.0.1:80:80 --name danwp danwp
script:
- docker ps | grep -q danwp
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=containah/danwp
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
