language: python
python:
- 2.7
env:
  global:
  - secure: VoZrvZSgpzhrBHEqS55+9f1Fg4tj3y3zT/wwZwmsWQe9YqU3hMKegWEW6JmS2DbucFQISRbwycshBiQuVVppMehZorHJfxdB7vQ0meSzts44CVoKEquySV8SCF+TvAE3uKXLfIvMU7UeFUBWq0cm0HA6T8/zjc1qB+WHZjTfiRAb+xu9yI/WkanlZoc4SoSX76D96KOZnqselYDtBRDx//wwdKiZ/WnLbpI8eYT7rYvoZcTGZHuovFXqbTb0v40wKAVxM0CfGzyWuEYxaoCjFmFIwhrrbBffvy/lMi/Lf5ebBPl6YJk+5AgMqyx1O7Db4c9lDNkiadWjewjEj6WrtGXsC0FSC9R8pCrRtedBKZYyLRM4n7LkWnCX6/AS8sf99lEwnOIJK3P0eeHP/o/jhD173nbRfb0cM4kU4RcYPBnsNl/m6V+h4ra32CWu9DLQlkkUdV7+8NJrAKCcxIVbwddMxKEBC+8r3+vQKcBW2Qn1/rEDR2O3gEsVqEQFDLckWN/WDx3bEkp/tQKZo/Prl6UopXVK0AkK60scV1FP4xOhyU0NFgQLwRi4wBXOtJXoKADM+sZYv5sHNSokXMW1fli4+hIO74iUYhMcQuP0A0cqZSwBXfeDu5sRHc/xXyWIpwHCgJo6xyp4/veWk+kKzJfA8bj6W7lw3QzScu+DKe0=
  - secure: VECT82Fqf9qV7Rwx4WFN+vIzg1bO2YI1/nH8bgMum4MDwESrImNXtXER8BdTI6FbrBdAaIwN6hxwmInsEXnH/4/LcuGb7HDQew4dAN+PUt5Hw6uaEYY59kJbapRBmaKPqg851slaKHZqloA3bhx/Q100ykcP0wmUrv7bptJAUSF8KZ14d6wymkw/QeZh+lN1FGPLPOZs2ck1RKkwq/W7WQPKz0s0/ZE/+Q/JCtbsK+2rXUe8dKvX3TAixZh0ND/PiktTwixpc5NC/+oO7OB9m309YclyWz2tA3Kh+O3QK9pf7pL/1dWsBjXQc7DtrkDCrxi3dWuX9DhccojN3ktFbM1qqQgrX1kVa+5aZvwrZYqUDahh6fat9VmCkkSE02cXupjx9yVXtP5mRkc75vXUiP5E9cE2LfS7+xLnn9AxxnSDHZUaaQuEuEOVBXZ66+mRsmtkITWOvmRv0rnEfz933JDhKgXGcJHeTz6cnuRaDCsnPlouBQNoMKEDwms476MQFV6qCch1amGQnO2km1UqRkbXXHsaRZB5MuRufjIrnciOFQgi1X56WxMiiEl8cn7Y70D1Y6YBdGDpSzy8AMJy3WTDy5J9PLsuqU0UEuBHmOoWB5PKNlD+UrLBz+3sZZ65MU+4a14lGSoSOVld9o4RoUAGuBS4+hgoiPan2kzJpfI=
services:
- docker
install:
- docker build -t danwp .
- docker run -d -p 127.0.0.1:80:80 --name danwp danwp
script:
- docker ps | grep -q danwp
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=containah/danwp
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u=$DOCKER_USER -p=$DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
