#!/usr/bin/with-contenv bash

# chown /usr/html
chown -R nginx:nginx /usr/html

mkdir -p /usr/logs/php-fpm
mkdir -p /usr/logs/nginx
mkdir -p /tmp/nginx
chown nginx /tmp/nginx
chmod +x /usr/bin/wait-for-it.sh

mkdir -p /usr/backup
chown -R nginx:nginx /usr/backup
