#!/usr/bin/with-contenv bash

# Install wp-cli if it doesn't exist.
if [ ! -f /usr/bin/wp ]; then
  curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/bin/wp && chmod 755 /usr/bin/wp && chown nginx:nginx /usr/bin/wp
else
  echo "wp-cli already installed"
  chmod 755 /usr/bin/wp && chown nginx:nginx /usr/bin/wp
fi
