#!/usr/bin/with-contenv bash

# v1 code, keeping for reference

#if [ -n "$WORDPRESS_DB" ] && [ ! -f /usr/html/wp-config.php ]; then
#  /usr/bin/wait-for-it.sh ${WORDPRESS_DB_HOST}:3306 --timeout=60 --strict -- wp config create --dbhost=$WORDPRESS_DB_HOST --dbname=$WORDPRESS_DB --dbuser=$WORDPRESS_DB_USER --dbpass=$WORDPRESS_DB_PASSWORD --path=/usr/html
#  chown -R nginx:nginx /usr/html
#else
#  echo "WP already configured or Environment Variables not set"
#  chown -R nginx:nginx /usr/html
#fi



# If variables are set and wp-config.php isn't in place ,create wp-config.php, otherwise leave it be.
if [ -n "$WORDPRESS_DB" ] && [ ! -f /usr/html/wp-config.php ]; then
  /usr/bin/wait-for-it.sh ${WORDPRESS_DB_HOST}:3306 --timeout=60
  wp config create --dbhost=$WORDPRESS_DB_HOST --dbname=$WORDPRESS_DB --dbuser=$WORDPRESS_DB_USER --dbpass=$WORDPRESS_DB_PASSWORD --path=/usr/html --extra-php <<PHP
// If we're behind a proxy server and using HTTPS, we need to alert Wordpress of that fact
// see also http://codex.wordpress.org/Administration_Over_SSL#Using_a_Reverse_Proxy
if (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
      \$_SERVER['HTTPS'] = 'on';
}
PHP
  chown -R nginx:nginx /usr/html
else
  echo "WP already configured or Environment Variables not set"
  chown -R nginx:nginx /usr/html
fi