#!/usr/bin/with-contenv bash

# If variables are set and wp-config.php isn't in place ,create wp-config.php, otherwise leave it be.
if [ -n "$WORDPRESS_DB" ] && [ ! -f /usr/html/wp-config.php ]; then
  /usr/bin/wait-for-it.sh ${WORDPRESS_DB_HOST}:3306 --timeout=60 --strict -- wp config create --dbhost=$WORDPRESS_DB_HOST --dbname=$WORDPRESS_DB --dbuser=$WORDPRESS_DB_USER --dbpass=$WORDPRESS_DB_PASSWORD --path=/usr/html
else
  echo "WP already configured or Environment Variables not set"
fi
